# Generated by Django 4.2.5 on 2023-09-16 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
